lib/teternikov_web/router.ex
defmodule TeternikovWeb.Router do
  use TeternikovWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Coherence.Authentication.Session)
  end

  pipeline :protected do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :admin_layout do
    plug(:put_layout, {TeternikovWeb.LayoutView, "one-solid-box.html"})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/" do
    pipe_through([:browser, :admin_layout])
    coherence_routes()
  end

  scope "/", TeternikovWeb do
    pipe_through([:protected, :admin_layout])

    scope "/admin" do
      resources("/pages", AdminPageController)
    end
  end

  scope "/", TeternikovWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", IndexController, :index)

    get("/*path", PageController, :show)
  end

  # Other scopes may use custom stacks.
  # scope "/api", TeternikovWeb do
  #   pipe_through :api
  # end
end

lib/teternikov_web/templates/admin_page/edit.html.eex
<h2>Edit Page</h2>

<%= render "form.html", Map.put(assigns, :action, admin_page_path(@conn, :update, @page)) %>

<span><%= link "Back", to: admin_page_path(@conn, :index) %></span>

lib/teternikov_web/templates/admin_page/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/teternikov_web/templates/admin_page/index.html.eex
<h2>Listing Pages</h2>

<table class="table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for page <- @pages do %>
    <tr>
      <td><%= page.url %></td>
      <td><%= page.title %></td>

      <td>
        <span><%= link "Show", to: admin_page_path(@conn, :show, page), class: "btn btn-default btn-xs" %></span>
      </td>
      <td>
        <span><%= link "Edit", to: admin_page_path(@conn, :edit, page), class: "btn btn-default btn-xs" %></span>
      </td>
      <td>
        <span><%= link "Delete", to: admin_page_path(@conn, :delete, page), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Page", to: admin_page_path(@conn, :new) %></span>

lib/teternikov_web/templates/admin_page/new.html.eex
<h2>New Page</h2>

<%= render "form.html", Map.put(assigns, :action, admin_page_path(@conn, :create)) %>

<span><%= link "Back", to: admin_page_path(@conn, :index) %></span>

lib/teternikov_web/templates/admin_page/show.html.eex
<h2>Show Page</h2>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @page.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @page.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @page.body %>
  </li>

</ul>

<span><%= link "Edit", to: admin_page_path(@conn, :edit, @page) %></span>
<span><%= link "Back", to: admin_page_path(@conn, :index) %></span>